### ISSUE TITLE
[DMS] - Downloading

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-dms-demo#273]
- [x] File can be downloaded if user chooses 'download' action from the actionmenu
![image](https://user-images.githubusercontent.com/6968860/43575031-06106964-9646-11e8-9d84-41a612c56b04.png)

- [ ] Files can be downloaded if user chooses 'download' action from the batch actionmenu
![image](https://user-images.githubusercontent.com/6968860/43575050-13e58ace-9646-11e8-9c56-60aa0bf28226.png)

**Comment by herflis** [comment]
@kultsar Downloading multiple files is not possible now and it needs back-end development. Is it a key feature in this phase of the dms development or could the button be removed from the ui and could making this feature be postponed?

**Comment by kultsar** [comment]
- [ ] Download action also executes the Versions action. Is this deliberately so, eg user should select the version they want to download? It happens when user finishes the download, but Versions popup stays there even when user cancels download. Not yet clear for me if this is a bug or not. Should I move this to a new issue?
- [ ] My gut feeling is that at this stage multiple download is not a key issue - yet. I would suggest that we only display download button if a single item is selected, but asked UX. Preliminary answer was that it is not a must have at this point. Can I move this question to a new issue so that we can concentrate on single item download in this issue?
- [ ] Actions menu download button does nothing even though user selected a file
![image](https://user-images.githubusercontent.com/39081660/43651656-431e74a6-9743-11e8-83b6-67448f76165c.png)
- [ ] Downloading directories: Download button appearance not consistent. Not displayed in right click action menu or 3dot action menu, but displayed in the actions menu in the header (same button in the picture above). Should be hidden at this point also, but asked UX how to handle this in later development stages.

**Comment by herflis** [comment]
1. It was a bug but it's now fixed on the test site
2. Make a separate issue for this feature pls
3. It is related two the previous thing (download multiple files). Since it will be moved into another issue and we postpone implementing multiple file download, I removed the icon from the batch action list
4. Since breadcrumb is now under construction, pls move this task/remark into the breadcrumb issue.
